apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-frontend
  template:
    metadata:
      labels:
        app: kube-frontend
    spec:
      containers:
        - name: kube-frontend
          image: kube-frontend:1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: kube-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 31000
  type: NodePort
