apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verification-api
  template:
    metadata:
      labels:
        app: verification-api
    spec:
      containers:
        - name: verification-api
          image: verification-api:1.0
          ports:
            - containerPort: 8081
          env:
            - name: POD_NAME
              value: "worker-2"
            - name: SQLITE_PATH
              value: "/data/issuance.sqlite"
          volumeMounts:
            - name: sqlite-storage
              mountPath: /data
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: kube-cred-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: verification-service
spec:
  selector:
    app: verification-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
